--מציג את פרטי הטיולים כולל מידע על התחבורה והיעדים
CREATE OR REPLACE VIEW TRIP_DETAILS AS
SELECT
    T.ID_TRIP,
    T.NAME AS TRIP_NAME,
    T.PRICE AS TRIP_PRICE,
    T.TRIP_DATE,
    TRAN.NUMBER_OF_PASSENGERS AS TRANSPORTATION_PASSENGERS,
    TRAN.DRIVER AS TRANSPORTATION_DRIVER,
    DEST.NAME AS DESTINATION_NAME,
    DEST.DESCRIPTION AS DESTINATION_DESCRIPTION
FROM
    TRIP T
JOIN
    TRANSPORTATION TRAN ON T.ID_TRANSPORTATION = TRAN.ID_TRANSPORTATION
JOIN
    DESTINATIONS DEST ON T.ID_TRIP = DEST.ID_TRIP;

SELECT * FROM TRIP_DETAILS;

--השגת פרטי טיול מסוים ותמצות המדריכים:
SELECT
    T.TRIP_NAME,
    T.TRIP_PRICE,
    T.TRIP_DATE,
    NVL(GL.GUIDED_BY_COUNT, 0) AS GUIDED_BY_COUNT
FROM
    TRIP_DETAILS T
LEFT JOIN
    (SELECT ID_TRIP, COUNT(*) AS GUIDED_BY_COUNT FROM GUIDED_BY GROUP BY ID_TRIP) GL
    ON T.ID_TRIP = GL.ID_TRIP
WHERE
    T.ID_TRIP = 101; 

--מחזיר את הטיול הכי יקר בכל שנה
SELECT
    T.ID_TRIP,
    T.NAME AS TRIP_NAME,
    T.PRICE AS TRIP_PRICE,
    EXTRACT(YEAR FROM T.TRIP_DATE) AS TRIP_YEAR
FROM TRIP T JOIN (SELECT
        EXTRACT(YEAR FROM TRIP_DATE) AS TRIP_YEAR,
        MAX(PRICE) AS MAX_PRICE
    FROM TRIP
    GROUP BY EXTRACT(YEAR FROM TRIP_DATE)
) MaxPrices
ON EXTRACT(YEAR FROM T.TRIP_DATE) = MaxPrices.TRIP_YEAR
    AND T.PRICE = MaxPrices.MAX_PRICE
ORDER BY TRIP_YEAR;

