--מציג את פרטי ההזמנות כולל פרטי העובדים הקשורים להזמנות
CREATE OR REPLACE VIEW WORKER_ORDERS AS
SELECT
    O.ORDERID,
    O.AMOUNT AS ORDER_AMOUNT,
    O.DATEOFSUPPLY,
    O.ORDERDATE,
    W.WORKERSNAME AS WORKER_NAME,
    W.WORKERSROLE AS WORKER_ROLE,
    W.WORKERSPHONE AS WORKER_PHONE,
    C.CUSTOMERSNAME AS CUSTOMER_NAME,
    C.CUSTOMERSPHONE AS CUSTOMER_PHONE
FROM
    ORDERS O
JOIN
    WORKERS W ON O.IDWO = W.IDWO
JOIN
    CUSTOMERS C ON O.IDCO = C.IDCO;

SELECT * FROM WORKER_ORDERS;


--מספר ההזמנות שכל עובד טיפל בו
SELECT
    W.workersname AS WORKER_NAME,
    COUNT(O.orderid) AS NUMBER_OF_ORDERS
FROM
    WORKER_ORDERS O
JOIN
    WORKERS W ON O.WORKER_NAME = W.WORKERSNAME
GROUP BY
    W.workersname
ORDER BY
    NUMBER_OF_ORDERS DESC;


--כל הלקוחות שסכום ההזמנה שלהם עולה על 1000
SELECT
    C.customersname AS CUSTOMER_NAME,
    C.customersphone AS CUSTOMER_PHONE,
    C.customersmail AS CUSTOMER_EMAIL,
    SUM(O.ORDER_AMOUNT) AS TOTAL_AMOUNT
FROM
    WORKER_ORDERS O
JOIN
    CUSTOMERS C ON O.CUSTOMER_NAME = C.CUSTOMERSNAME
GROUP BY
    C.customersname,
    C.customersphone,
    C.customersmail
HAVING
    SUM(O.ORDER_AMOUNT) > 1000
ORDER BY
    TOTAL_AMOUNT DESC;

