INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8933, 'GAAD4Gvz@gmail.com', 0526956196, 'Afternoon', 1, 'Elias Martin');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8919, '6nH7yatv@gmail.com', 0546597191, 'Evening', 2, 'Oliver Young');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 7696, 'gi7BAUJU@gmail.com', 0531149208, 'Morning', 3, 'Jackson Murphy');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 11895, 'Y5kCLDmE@gmail.com', 0539048194, 'Afternoon', 4, 'Elijah Robinson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 8712, '1hYiTP6g@gmail.com', 0536732435, 'Evening', 5, 'David Carter');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 14350, 'oiTZv76k@gmail.com', 0571796738, 'Morning', 6, 'Claire Miller');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 14530, 'eZslowdS@gmail.com', 0535796510, 'Evening', 7, 'Aurora Turner');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 10118, 'Jm4gMp5R@gmail.com', 0569391226, 'Evening', 8, 'Emma Wright');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 10279, 'x4XJknNp@gmail.com', 0572740432, 'Morning', 9, 'Amelia Campbell');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 12829, 'EsdgtOYs@gmail.com', 0576945371, 'Morning', 10, 'Sophia King');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 9180, 'WCduuOBr@gmail.com', 0536342312, 'Evening', 11, 'Olivia Scott');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 9575, 'UHRBwxhc@gmail.com', 0509286034, 'Evening', 12, 'Harper Young');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 10727, 'A9qO1tjN@gmail.com', 0595522957, 'Morning', 13, 'Henry Lopez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 14402, '78OofnqK@gmail.com', 0591200672, 'Afternoon', 14, 'Benjamin Hall');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8113, '1gDaAeE9@gmail.com', 0583586434, 'Afternoon', 15, 'William Jones');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8609, 'TgXQrIAR@gmail.com', 0552337692, 'Morning', 16, 'Sophia Anderson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 12521, 'BwlXs3S0@gmail.com', 0514103974, 'Afternoon', 17, 'Claire Miller');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 8627, 'IeI0C6pp@gmail.com', 0529814090, 'Evening', 18, 'Elizabeth Lee');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 10277, 'YE1J0PXg@gmail.com', 0508291301, 'Afternoon', 19, 'Avah Lewis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8961, 'pqMgEsc5@gmail.com', 0504357854, 'Afternoon', 20, 'Luna Phillips');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 10323, 'PUFX199h@gmail.com', 0572260269, 'Afternoon', 21, 'Violet Young');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 12730, 'PQrlU0DH@gmail.com', 0503386039, 'Morning', 22, 'Avery Davis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 9758, '8BCFLbEI@gmail.com', 0533375134, 'Afternoon', 23, 'Oliver Turner');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 9366, 'An40xdkZ@gmail.com', 0597321717, 'Afternoon', 24, 'Aaliyah Carter');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 10977, 'm20jWqa7@gmail.com', 0557836241, 'Evening', 25, 'Harper Baker');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 7695, 'AiX7Iylg@gmail.com', 0565811105, 'Evening', 26, 'Amelia Diaz');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 12888, 'xIo5Rzc4@gmail.com', 0591157312, 'Afternoon', 27, 'Isabella Wright');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 8811, 'aR6JSBjz@gmail.com', 0548441159, 'Afternoon', 28, 'Liam Nelson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 12976, 'vyTAEOkY@gmail.com', 0562938459, 'Afternoon', 29, 'Liam Smith');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 11248, 'LXPribsA@gmail.com', 0528746755, 'Afternoon', 30, 'Aaliyah Hernandez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 11178, 'V463Osef@gmail.com', 0582066880, 'Morning', 31, 'Liam Young');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 8575, '96k9xQ2o@gmail.com', 0538201036, 'Evening', 32, 'Abigail Moore');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 7938, 'L1E3kf4V@gmail.com', 0570649166, 'Evening', 33, 'Liam Phillips');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 12484, 'W2XH0zYT@gmail.com', 0559682130, 'Evening', 34, 'Evelyn Campbell');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 13711, 'TwnwCmkt@gmail.com', 0542467998, 'Morning', 35, 'Mason Miller');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 9309, 'yrybonQD@gmail.com', 0576716252, 'Morning', 36, 'Abigail Walker');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 12978, 'jP8RHiOr@gmail.com', 0562485543, 'Morning', 37, 'Elizabeth Scott');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 9586, 'y33H0Fak@gmail.com', 0531392041, 'Evening', 38, 'William Jones');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 9464, 'c6hSZvJG@gmail.com', 0519970445, 'Evening', 39, 'William Rodriguez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 10961, 'tamyBCgo@gmail.com', 0550479868, 'Afternoon', 40, 'Ava Wright');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 13431, 'rEvppcLv@gmail.com', 0522955072, 'Afternoon', 41, 'Evelyn Rodriguez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 13288, '8Vp9sFwY@gmail.com', 0577536719, 'Afternoon', 42, 'Elijah Wood');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 12635, 'j5c9aE2Y@gmail.com', 0563747501, 'Evening', 43, 'Jackson Bell');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 12807, 'LpC6obrr@gmail.com', 0525879367, 'Evening', 44, 'James Campbell');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 13882, 'fr07YdqE@gmail.com', 0538306078, 'Morning', 45, 'Camila Young');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 14161, 'R7tQK1Sr@gmail.com', 0526704387, 'Morning', 46, 'Mateo Robinson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 13351, 'dgz3BOmZ@gmail.com', 0518269520, 'Afternoon', 47, 'Alexander Mitchell');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 10789, 'j4CbgqnF@gmail.com', 0558056698, 'Morning', 48, 'Henry Scott');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 14772, 'moQMLCBt@gmail.com', 0599394146, 'Afternoon', 49, 'Lucas Wright');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 9844, '2hBAWI0n@gmail.com', 0554253415, 'Morning', 50, 'Mason Diaz');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 9148, 'BX18EyNn@gmail.com', 0509320960, 'Morning', 51, 'Harper Clark');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 11269, '1sqQ1w5V@gmail.com', 0515633392, 'Afternoon', 52, 'Lucas Miller');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 9533, 'LY7TfiiT@gmail.com', 0506938505, 'Evening', 53, 'Benjamin Walker');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 9326, 'LBEDM70b@gmail.com', 0589856059, 'Morning', 54, 'Charlotte Allen');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 11630, 'yo7rv2m3@gmail.com', 0560529370, 'Morning', 55, 'Mia Martin');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 11774, 'OMBpYwxP@gmail.com', 0584697110, 'Afternoon', 56, 'William Williams');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 10975, 'cIRI8C7I@gmail.com', 0517804862, 'Evening', 57, 'Liam Moore');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8665, 'ZQzzg1z8@gmail.com', 0514869393, 'Morning', 58, 'Charlotte Robinson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 7683, '1aEjz3kV@gmail.com', 0530469739, 'Evening', 59, 'Benjamin Campbell');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 8374, 'Y3KC4Cwy@gmail.com', 0514138556, 'Evening', 60, 'Avery Diaz');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 11220, 'ZeJhzX67@gmail.com', 0533642917, 'Afternoon', 61, 'Avery Allen');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 13886, 'ZL0p4XNn@gmail.com', 0551519517, 'Afternoon', 62, 'Benjamin Wright');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 10830, 'z2VMinVL@gmail.com', 0556545258, 'Morning', 63, 'Michael Robinson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8913, '2OnnjRrd@gmail.com', 0559270669, 'Evening', 64, 'Emma Johnson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 7527, 'jE3hUxyX@gmail.com', 0571219730, 'Afternoon', 65, 'Julian Hall');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 9932, 'QaxWvBKD@gmail.com', 0576451537, 'Evening', 66, 'Julian Harris');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 12215, 'wMZR4ZpO@gmail.com', 0581288119, 'Afternoon', 67, 'Michael Rodriguez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 12170, 'mbvL0VI6@gmail.com', 0578763693, 'Evening', 68, 'Sofia Thomas');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 10540, 'zsGxd509@gmail.com', 0518611303, 'Morning', 69, 'Charlotte Hall');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 10511, 'PdtASed0@gmail.com', 0593795124, 'Morning', 70, 'Sofia Wright');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 13331, 'gMhuzYc0@gmail.com', 0505817467, 'Morning', 71, 'Noah Rodriguez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 14284, 'g9qHbSom@gmail.com', 0506487681, 'Afternoon', 72, 'Charlotte Lewis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 9945, 'b28ERxnM@gmail.com', 0535336993, 'Evening', 73, 'Noah Young');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 14524, 'UVWpEaTp@gmail.com', 0579430329, 'Morning', 74, 'Evelyn Wright');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 8497, 's2af13fR@gmail.com', 0541135262, 'Afternoon', 75, 'Sophia Williams');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 11077, 'FqYIP34w@gmail.com', 0516256511, 'Afternoon', 76, 'Mason Murphy');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 12885, 'AzIy1pPl@gmail.com', 0559027760, 'Morning', 77, 'Elias Gonzalez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8059, '3lBcPXTY@gmail.com', 0558713988, 'Evening', 78, 'James Wood');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 12201, 'tEXa18Z0@gmail.com', 0565641120, 'Morning', 79, 'Mason Walker');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 8051, 'YnbzsL8k@gmail.com', 0514677999, 'Morning', 80, 'Lucas Green');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 10016, '6vuL1i45@gmail.com', 0592891900, 'Morning', 81, 'Camila Robinson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 11313, 'R3XSwBgh@gmail.com', 0534674181, 'Evening', 82, 'James Moore');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 13596, '1S7eqI8N@gmail.com', 0527521685, 'Afternoon', 83, 'Aaliyah Gonzalez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 13673, 'iiA9miYG@gmail.com', 0590019845, 'Morning', 84, 'Liam Davis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8972, 'huBX75Wh@gmail.com', 0513678912, 'Morning', 85, 'Evelyn Diaz');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 9461, 'EMGWCTS5@gmail.com', 0589669940, 'Afternoon', 86, 'Liam Garcia');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 14540, 'oz8Nb2bz@gmail.com', 0557015726, 'Evening', 87, 'Charlotte Phillips');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 9141, '4kl334Bn@gmail.com', 0531052830, 'Afternoon', 88, 'Mason Phillips');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 13732, 'yMVMCZ7h@gmail.com', 0555702962, 'Evening', 89, 'William Murphy');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 12031, '5f1WD2Xo@gmail.com', 0511894314, 'Afternoon', 90, 'Avery Lewis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 12448, '4Wu71MDW@gmail.com', 0578702453, 'Afternoon', 91, 'Amelia Rodriguez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 10246, 'XMCOe0fe@gmail.com', 0594196850, 'Afternoon', 92, 'James Thomas');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 10278, 'oFS0IBpL@gmail.com', 0591233538, 'Evening', 93, 'Emily Lopez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 7806, 'VDNcyBOx@gmail.com', 0536391125, 'Evening', 94, 'Charlotte Young');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 9260, 'rDjEC4YH@gmail.com', 0573536531, 'Afternoon', 95, 'Aaliyah Lewis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 14311, 'Ddz5l3nJ@gmail.com', 0515834600, 'Evening', 96, 'Mia Nelson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 13960, 'TSDFFn7m@gmail.com', 0518387970, 'Afternoon', 97, 'Evelyn Smith');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 13827, 'IliqJvrF@gmail.com', 0520689705, 'Morning', 98, 'Sophia Scott');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8713, 'vN40wQJS@gmail.com', 0592974002, 'Morning', 99, 'Zoe King');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 14283, 'vYFi1BNC@gmail.com', 0586450881, 'Morning', 100, 'Mason Thomas');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 8072, 'UT4TU1O0@gmail.com', 0574137010, 'Evening', 101, 'Elizabeth Cruz');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8325, 'UiUYf8Kr@gmail.com', 0555217403, 'Afternoon', 102, 'Evelyn Baker');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 14993, 'wR9vUehQ@gmail.com', 0509569472, 'Evening', 103, 'Alexander Clark');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 12603, 'OeJNOmXf@gmail.com', 0524097816, 'Morning', 104, 'Sophia Harris');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 14802, 'clAJN0Nh@gmail.com', 0534741037, 'Evening', 105, 'Evelyn Turner');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 14625, 'G0uVF44A@gmail.com', 0545070072, 'Afternoon', 106, 'Mia Hall');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 8656, 'RGAB4ucq@gmail.com', 0501126493, 'Afternoon', 107, 'Mason Scott');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 14090, 'TYgdOxLE@gmail.com', 0548989383, 'Morning', 108, 'Ethan Harris');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 14746, 'aGUQeB5c@gmail.com', 0555318955, 'Afternoon', 109, 'Jackson Clark');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 12923, 'XWUIykwf@gmail.com', 0565578192, 'Afternoon', 110, 'Ethan Adams');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 10984, 'qfwMbMps@gmail.com', 0518829946, 'Morning', 111, 'Evelyn Roberts');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 13586, 'aws8ige6@gmail.com', 0527584920, 'Afternoon', 112, 'Lucas Bell');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 14429, 'aYZ6sirl@gmail.com', 0582531445, 'Evening', 113, 'Logan Young');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 13857, 'jNnxEo0t@gmail.com', 0595609972, 'Afternoon', 114, 'Zoe Harris');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 9403, 'JMRhxR4E@gmail.com', 0512946955, 'Afternoon', 115, 'Sophia Moore');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 9912, 'WpbRE2Bg@gmail.com', 0528942704, 'Afternoon', 116, 'Aurora Wilson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 8570, 'SydIGlDu@gmail.com', 0573069644, 'Afternoon', 117, 'Luna Moore');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 10361, 'xomIejjz@gmail.com', 0543442604, 'Afternoon', 118, 'Oliver Wilson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 13270, 'srcIaymu@gmail.com', 0531311411, 'Morning', 119, 'Claire Moore');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 9735, 'bhMGH8Ps@gmail.com', 0546038928, 'Morning', 120, 'Ethan Jackson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 8371, 'eAajFqMr@gmail.com', 0517544772, 'Afternoon', 121, 'Jackson Lee');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 10085, 'Q9v3OY7v@gmail.com', 0590831902, 'Afternoon', 122, 'Maverick Thomas');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 11553, 'xlUR5WMd@gmail.com', 0574811782, 'Evening', 123, 'Charlotte Brown');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 7815, 'aZ1FtSUv@gmail.com', 0566142031, 'Evening', 124, 'Scarlett Lewis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 9487, 'AZFIAUPh@gmail.com', 0586384716, 'Morning', 125, 'Ethan Moore');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 13483, 'tgyP87nU@gmail.com', 0566625064, 'Morning', 126, 'Mason Johnson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 13319, 'cZbJD4ZV@gmail.com', 0541758860, 'Morning', 127, 'Harper Allen');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 12537, '8DI1thph@gmail.com', 0505065140, 'Morning', 128, 'Scarlett Allen');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 13783, 'IEK1LKdt@gmail.com', 0596851087, 'Evening', 129, 'Lucas Campbell');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 13250, 'ivjD1J4C@gmail.com', 0589054493, 'Morning', 130, 'Ella Thomas');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 11717, 'VlsjjorT@gmail.com', 0595616828, 'Morning', 131, 'Emma Hernandez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 8807, 'rPPxv09W@gmail.com', 0592759653, 'Afternoon', 132, 'Mason Young');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 8994, 'k4MydnyK@gmail.com', 0511439653, 'Afternoon', 133, 'Avery Johnson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 11320, 'ucGpH8gv@gmail.com', 0544503063, 'Morning', 134, 'Matthew Davis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 7850, 'agKPJ3wb@gmail.com', 0542738027, 'Afternoon', 135, 'Ethan Robinson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 11209, 'nHwPrbmO@gmail.com', 0584238863, 'Morning', 136, 'Logan Allen');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 12511, 'xs4zal62@gmail.com', 0560033171, 'Evening', 137, 'Mason Scott');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 11966, 'zxx8ybq2@gmail.com', 0504085308, 'Afternoon', 138, 'Ella Turner');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 12619, 'vZHo0yRM@gmail.com', 0558600621, 'Evening', 139, 'Mason Lopez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 13858, 'vsU037yi@gmail.com', 0570833546, 'Afternoon', 140, 'Aaliyah Walker');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 11922, 'JMqdDBMT@gmail.com', 0537566076, 'Evening', 141, 'Olivia Mitchell');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 13432, 'pJPqEnHH@gmail.com', 0537021434, 'Afternoon', 142, 'Ethan Nelson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 12410, 'EFUAeDcN@gmail.com', 0548756040, 'Morning', 143, 'Alexander Miller');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 13302, 'sDXsGKz7@gmail.com', 0586233230, 'Morning', 144, 'Mason King');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 8613, 'I7HPYKIv@gmail.com', 0560352029, 'Afternoon', 145, 'Ethan Hall');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 13734, 'pML4bvqf@gmail.com', 0565054766, 'Morning', 146, 'Elias Carter');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 10805, '54iAcoEo@gmail.com', 0596145348, 'Afternoon', 147, 'Emily Turner');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 11703, 'lWCpHFXn@gmail.com', 0559362076, 'Evening', 148, 'Charlotte Rodriguez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 14417, 'LaPkhLQz@gmail.com', 0575258169, 'Morning', 149, 'Mason Clark');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 12917, 'WxnydswT@gmail.com', 0527595994, 'Afternoon', 150, 'Elias Miller');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 12555, 'lgolGf2Y@gmail.com', 0525772289, 'Afternoon', 151, 'James Carter');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 11227, 'If2sIZSO@gmail.com', 0544766314, 'Afternoon', 152, 'Charlotte Hall');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 12294, 'vTyQEpqy@gmail.com', 0534884493, 'Evening', 153, 'Oliver Davis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 13593, 'Wk1Ilwzs@gmail.com', 0597121496, 'Morning', 154, 'Emma Turner');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 12565, 'F5GvjfaO@gmail.com', 0594766367, 'Morning', 155, 'Liam Moore');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 7814, 'j9jLB4Hv@gmail.com', 0574160322, 'Afternoon', 156, 'James Garcia');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 11328, 'vxEoIODK@gmail.com', 0527686916, 'Afternoon', 157, 'Mason Jackson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 13848, '09bBLCcP@gmail.com', 0562694889, 'Morning', 158, 'Mason Lee');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 10780, '0V5RCVD8@gmail.com', 0577044786, 'Afternoon', 159, 'Avah Robinson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 8015, 'CQyYvjmI@gmail.com', 0523297388, 'Morning', 160, 'Abigail Young');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 14720, 'aoleN6Vt@gmail.com', 0509334722, 'Morning', 161, 'William Moore');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 12022, 'HV1XooNy@gmail.com', 0513601393, 'Afternoon', 162, 'William Walker');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 10223, '0ZxDdRwA@gmail.com', 0507855207, 'Evening', 163, 'Ethan Hernandez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 13575, 'G58rumS1@gmail.com', 0533322083, 'Afternoon', 164, 'Olivia Green');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 9174, 'GooEaANg@gmail.com', 0527399786, 'Afternoon', 165, 'Evelyn Diaz');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 14644, '6LlVevcq@gmail.com', 0513149746, 'Evening', 166, 'Stella Rodriguez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 9336, 'QVsHI8BY@gmail.com', 0546426321, 'Afternoon', 167, 'Avery Walker');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 9253, 'a1biOq9X@gmail.com', 0525700652, 'Afternoon', 168, 'Avah Davis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8914, 'VWflwFhY@gmail.com', 0532528104, 'Evening', 169, 'Lucas Walker');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 14797, 'yptSwt2n@gmail.com', 0553610071, 'Evening', 170, 'William Clark');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 10163, 'jeEdXLde@gmail.com', 0505214713, 'Evening', 171, 'Mason Scott');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 7650, 'EV2GPBGD@gmail.com', 0563189422, 'Morning', 172, 'Jackson Diaz');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 12444, 'fRfEc48B@gmail.com', 0591574501, 'Evening', 173, 'Henry Davis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 11515, 'fB3pXp5X@gmail.com', 0510343881, 'Morning', 174, 'Emma Clark');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 11745, 'C1eJDe9d@gmail.com', 0517188523, 'Evening', 175, 'Isabella Allen');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 10706, 'Nh6euYyz@gmail.com', 0512850072, 'Afternoon', 176, 'Ava Wright');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 9466, 'IAKsJUuX@gmail.com', 0506139868, 'Afternoon', 177, 'Emily Phillips');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 11132, 'xd1DVx7G@gmail.com', 0517827818, 'Afternoon', 178, 'Elijah Allen');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 11216, '1YvanWcs@gmail.com', 0527082662, 'Afternoon', 179, 'Ava Lopez');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 12052, 'qLuHEmxt@gmail.com', 0575352411, 'Morning', 180, 'David Allen');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 9791, 'Sse3B30V@gmail.com', 0506840153, 'Afternoon', 181, 'James Roberts');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 12863, '15Kj3rKL@gmail.com', 0578405706, 'Evening', 182, 'Noah Anderson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 13017, 'Du7es9Vi@gmail.com', 0560462040, 'Morning', 183, 'Liam Roberts');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 7634, 'E3jatcrq@gmail.com', 0528570438, 'Evening', 184, 'Alexander Wright');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 13286, 'zvNKJpct@gmail.com', 0596291725, 'Afternoon', 185, 'Lucas Campbell');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 7800, '3VyXMrJI@gmail.com', 0566764860, 'Afternoon', 186, 'Logan Hall');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Customer Service Representative', 14213, 'epsYzeoF@gmail.com', 0533303640, 'Morning', 187, 'Noah Garcia');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 13598, 'cq9RuSZY@gmail.com', 0590571518, 'Morning', 188, 'Mason Williams');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 12204, 'JOILxHhW@gmail.com', 0516385582, 'Afternoon', 189, 'Lucas Robinson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 13835, 'fPmwCbFX@gmail.com', 0558461953, 'Morning', 190, 'Mia Garcia');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 8696, 'oyCZpce5@gmail.com', 0528718737, 'Morning', 191, 'Emma Clark');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 13411, 'Gb0pNOAc@gmail.com', 0542487569, 'Evening', 192, 'Sophia Phillips');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Prepress Technician', 8385, 'bLCXDjJj@gmail.com', 0524998883, 'Afternoon', 193, 'Aaliyah Lee');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 12813, 'eQxsMA9I@gmail.com', 0575134006, 'Afternoon', 194, 'Alexander Nelson');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 9990, 'SIItpMkl@gmail.com', 0561817795, 'Morning', 195, 'Logan Harris');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES ('Press Operator', 8079, '2V7QmuiF@gmail.com', 0534931109, 'Morning', 196, 'Ava Miller');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 11268, 'El96HfMS@gmail.com', 0500409706, 'Morning', 197, 'Sofia Lewis');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 7736, 'oxYWZ70x@gmail.com', 0531691969, 'Evening', 198, 'Violet Miller');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 11222, 'ncYwERq3@gmail.com', 0553931039, 'Morning', 199, 'Lucas Williams');
INSERT INTO Workers (WorkersRole, Wage, WorkersMail, WorkersPhone, Shift, IdWo, WorkersName) VALUES (' Graphic Designer', 8631, 'rpKkYKgY@gmail.com', 0562634725, 'Morning', 200, 'Logan Gonzalez'); 
commit;
